export const wilayas = [
    "Adrar",
    "Ain-Defla",
    "Ain-Temouchent",
    "Alger",
    "Annaba",
    "Batna",
    "Bechar",
    "Bejaia",
    "Biskra",
    "Blida",
    "Bordj Baji Mokhtar",
    "Bordj Bou Arrer",
    "Bouira",
    "Boumerdes",
    "Béni Abbès",
    "Chlef",
    "Constantine",
    "Djanet",
    "Djelfa",
    "El Bayadh",
    "El M'Ghair",
    "El Menia",
    "El Oued",
    "El-Tarf",
    "Ghardaia",
    "Guelma",
    "Illizi",
    "In Guezzam",
    "In Salah",
    "Jijel",
    "Khenchela",
    "Laghouat",
    "M'Sila",
    "Mascara",
    "Medea",
    "Mila",
    "Mostaganem",
    "Naama",
    "Oran",
    "Ouargla",
    "Ouled Djellal",
    "Oum El Bouaghi",
    "Relizane",
    "Saida",
    "Setif",
    "Sidi Bel Abbes",
    "Skikda",
    "Souk-Ahras",
    "Tamanrasset",
    "Tebessa",
    "Tiaret",
    "Timimoun",
    "Tindouf",
    "Tipaza",
    "Tissemsilt",
    "Tizi Ouzou",
    "Tlemcen",
    "Touggourt"
]; 